config/routes.rb
UnepWcmcOrg::Application.routes.draw do

  as :user do
    patch '/user/confirmation' => 'confirmations#update', via: :patch, as: :update_user_confirmation
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'registrations#update', :as => 'user_registration'
  end

  devise_for :users, :controllers => { :confirmations => "confirmations" }, skip: [:registrations]

  post '/donate/create', to: 'checkouts#create', as: 'checkouts'

  get "/about-us/news-archive" => redirect("/news")

  namespace :admin do
    resources :employees do
      collection do
        put :reorder
      end
    end

    resources :aboutus_pages, except: [:new, :destroy]

    resources :expertise_pages

    resources :news_items do
      collection do
        put :reorder
      end
    end

    resources :programmes, except: [:show]

    resources :featured_projects do
      collection do
        put :reorder
      end
    end

    resources :datasets do
      collection do
        put :reorder
      end
    end

    resources :policies do
      collection do
        put :reorder
      end
    end

    resources :vacancies do
      collection do
        put :reorder
      end
    end

    resources :users
  end

  resources :forms, only: [] do
    resources :submissions, path: "applications", except: [:index]
  end

  resources :job_applications, only: [:index, :show, :destroy]

  get '/download_all_applications_zip/:id', controller: :job_applications, action: :download_all_applications_zip, as: 'download_all_applications_zip'
  get '/download_all_applications_csv/:id', controller: :job_applications, action: :download_all_applications_csv, as: 'download_all_applications_csv'
  get '/download_application_zip/:id', controller: :job_applications, action: :download_application_zip, as: 'download_application_zip'

  namespace :api do
    resources :geoip, only: [:index]
    resources :countries, only: [:index]
    resources :employees, only: [:index]
  end

  get 'test_exception_notifier', controller: :application, action: :test_exception_notifier

  comfy_route :cms_admin, :path => '/admin'
  comfy_route :cms, :path => '/', :sitemap => true
end

app/controllers/admin/aboutus_pages_controller.rb
class Admin::AboutusPagesController < Admin::PageResourcesController

  private

  def save_resources
    @page.save
  end

  def site_identifier
    'about-us'
  end

  def layout_identifier
    'about-us'
  end

end

app/views/comfy/admin/aboutus_pages/_index_branch.html.haml
- page ||= index_branch

%li{:id => dom_id(page)}
  .item
    .icon{:class => page.is_published?? 'published' : 'draft'}

    .btn-group
      = link_to t('.edit'), edit_admin_aboutus_page_path(page), :class => 'btn btn-small'

    .item-content
      .item-title
        = link_to page.label, edit_admin_aboutus_page_path(page), :class => 'item-label'
      .item-meta
        = link_to page.url, page.url, :target => '_blank'
        = render partial: "editions", locals: {page: page}

app/views/comfy/admin/aboutus_pages/index.html.haml
.page-header
  %h2 About us

= comfy_form_for @page, :as => :page, url: admin_aboutus_page_path(@page), :html => {:multipart => true} do |form|
  = render form

= render 'admin/cms/partials/pages_before'

%ul.list.sortble
  = render :partial => 'index_branch', :collection => @pages, :editions => @editions

= render 'admin/cms/partials/pages_after'