config/routes.rb
UnepWcmcOrg::Application.routes.draw do

  as :user do
    patch '/user/confirmation' => 'confirmations#update', via: :patch, as: :update_user_confirmation
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'registrations#update', :as => 'user_registration'
  end

  devise_for :users, :controllers => { :confirmations => "confirmations" }, skip: [:registrations]

  post '/donate/create', to: 'checkouts#create', as: 'checkouts'

  get "/about-us/news-archive" => redirect("/news")

  namespace :admin do
    resources :employees do
      collection do
        put :reorder
      end
    end

    resources :aboutus_pages, except: [:new, :destroy]

    resources :expertise_pages

    resources :news_items do
      collection do
        put :reorder
      end
    end

    resources :programmes, except: [:show]

    resources :featured_projects do
      collection do
        put :reorder
      end
    end

    resources :datasets do
      collection do
        put :reorder
      end
    end

    resources :policies do
      collection do
        put :reorder
      end
    end

    resources :vacancies do
      collection do
        put :reorder
      end
    end

    resources :users
  end

  resources :forms, only: [] do
    resources :submissions, path: "applications", except: [:index]
  end

  resources :job_applications, only: [:index, :show, :destroy]

  get '/download_all_applications_zip/:id', controller: :job_applications, action: :download_all_applications_zip, as: 'download_all_applications_zip'
  get '/download_all_applications_csv/:id', controller: :job_applications, action: :download_all_applications_csv, as: 'download_all_applications_csv'
  get '/download_application_zip/:id', controller: :job_applications, action: :download_application_zip, as: 'download_application_zip'

  namespace :api do
    resources :geoip, only: [:index]
    resources :countries, only: [:index]
    resources :employees, only: [:index]
  end

  get 'test_exception_notifier', controller: :application, action: :test_exception_notifier

  comfy_route :cms_admin, :path => '/admin'
  comfy_route :cms, :path => '/', :sitemap => true
end

app/controllers/admin/datasets_controller.rb
class Admin::DatasetsController < Admin::PageResourcesController
  before_action :set_fields, only: [:edit, :create]

  private

  def save_resources
    if @page.save
      url_fields.save
      file_fields.save
    end
  end

  def site_identifier
    'resources-and-data'
  end

  def layout_identifier
    'dataset'
  end

  def set_fields
    @url_fields ||= DatasetUrlField.for_dataset(@page)
    @file_fields ||= DatasetFileField.for_dataset(@page)
  end

  def dataset_url_fields_params
    params[:urlFieldForms].try(:values) || []
  end

  def dataset_file_fields_params
    params[:fileFieldForms].try(:values) || []
  end

  def file_fields
    DatasetFieldsBuilder.new(fields_params: dataset_file_fields_params, dataset: @page, type: "DatasetFileField")
  end

  def url_fields
    DatasetFieldsBuilder.new(fields_params: dataset_url_fields_params, dataset: @page, type: "DatasetUrlField")
  end

end

app/views/admin/datasets/_custom_fields.html.haml
.form-group{ "ng-app" => "DatasetFieldForm", "ng-controller" => "DatasetFieldCtrl", "ng-init" => "init(#{render partial: "dataset_url_fields", formats: :json}, #{render partial: "dataset_file_fields", formats: :json})"}
  .form-group{ "ng-repeat" => "form in urlFieldForms", "ng-show" => "!form.removed" }

    %label.control-label.col-sm-2 Url
    .col-sm-10.col-sm-offset-2
      .form-group
        %label.control-label.col-sm-2{:for => "urlFieldForms[{{ urlFieldFormIndex() }}][label]"} Label
        .col-sm-8
          %select{ "ui-select2" => true, "ng-model" => "form.label", "name" => "urlFieldForms[{{ urlFieldFormIndex() }}][label]", "ng-change" => "clearCustomLabel(urlFieldFormIndex(), 'url')" }
            %option{"ng-repeat" => "option in urlSelectDefaultOptions", :value => "{{ option }}", "ng-selected" => "form.label == '{{ option }}' "}
              {{ option }}
            %option{ :value => "Custom label", "ng-selected" => "form.label == 'Custom label'" }
              Custom label
        .col-sm-10.col-sm-offset-2
          %input{ :type => "text", "ng-model" => "form.custom_label", :name => "urlFieldForms[{{ urlFieldFormIndex() }}][custom_label]", "ng-show" => "showLabelInput(form)"}
          %input{ :type => "hidden", "ng-model" => "form.id", :name => "urlFieldForms[{{ urlFieldFormIndex() }}][id]", "ng-if" => "form.id", "value" => "{{ form.id }}"}
          %input{ :type => "hidden", "ng-model" => "form.removed", :name => "urlFieldForms[{{ urlFieldFormIndex() }}][removed]", "ng-if" => "form.removed", "value" => "{{ form.removed }}"}

      .form-group
        %label.control-label.col-sm-2{:for => "urlFieldForms[{{ urlFieldFormIndex() }}][url]"} Url
        .col-sm-8
          %input{ :type => "text", "ng-model" => "form.url", :name => "urlFieldForms[{{ urlFieldFormIndex() }}][url]"}
      .form-group
        .col-sm-10.col-sm-offset-2
          %input.btn.btn-danger{:type => "button", :value => "Remove", "ng-click" => "removeUrlFieldForm(urlFieldFormIndex())" }

  .form-group
    .col-sm-10.col-sm-offset-2
      %input.btn.btn-default{:type => "button", :value => "Add a link", "ng-click" => "addUrlField()"}


  .form-group{ "ng-repeat" => "form in fileFieldForms", "ng-show" => "!form.removed" }

    %label.control-label.col-sm-2 File
    .col-sm-10.col-sm-offset-2
      .form-group
        %label.control-label.col-sm-2{:for => "fileFieldForms[{{ urlFieldFormIndex() }}][label]"} Label
        .col-sm-8
          %select{ "ui-select2" => true, "ng-model" => "form.label", "name" => "fileFieldForms[{{ fileFieldFormIndex() }}][label]", "ng-change" => "clearCustomLabel(fileFieldFormIndex())" }
            %option{ :value => "Download", "ng-selected" => "form.label == 'Download'"}
              Download 
            %option{:value => "Custom label", "ng-selected" => "form.label == 'Custom label'" }
              Custom label
        .col-sm-10.col-sm-offset-2
          %input{ :type => "text", "ng-model" => "form.custom_label", :name => "fileFieldForms[{{ fileFieldFormIndex() }}][custom_label]", "ng-show" => "showLabelInput(form)"}
          %input{ :type => "hidden", "ng-model" => "form.id", :name => "fileFieldForms[{{ fileFieldFormIndex() }}][id]", "ng-if" => "form.id", "value" => "{{ form.id }}"}
          %input{ :type => "hidden", "ng-model" => "form.removed", :name => "fileFieldForms[{{ fileFieldFormIndex() }}][removed]", "ng-if" => "form.removed", "value" => "{{ form.removed }}"}

      .form-group
        %label.control-label.col-sm-2{:for => "fileFieldForms[{{ fileFieldFormIndex() }}][file]"} File
        .col-sm-8
          %input{ :type => "file", "ng-model" => "form.file", :name => "fileFieldForms[{{ fileFieldFormIndex() }}][file]" }
          %a{ :href => "{{ form.url }}", "ng-if" => "form.url"}
            %p {{ form.filename }}
      .form-group
        .col-sm-10.col-sm-offset-2
          %input.btn.btn-danger{:type => "button", :value => "Remove", "ng-click" => "removeFileFieldForm(fileFieldFormIndex())" }

  .form-group
    .col-sm-10.col-sm-offset-2
      %input.btn.btn-default{:type => "button", :value => "Add a file", "ng-click" => "addFileField()" }

app/views/admin/datasets/_form.html.haml
- content_for :right_column do
  #form-save.box
    %label.checkbox.inline
      %input{:type => 'checkbox'}
      = ::Cms::Page.human_attribute_name(:is_published)
    %button.btn.btn-small.btn-primary.pull-right
  = render :partial => 'admin/cms/files/index'

= render 'admin/cms/partials/page_form_before', :object => form

= form.text_field :label, :data => {:slugify => @page.new_record?}

- unless @site.pages.count == 0 || @site.pages.root == @page
  = form.text_field :slug, :data => {:slug => true}
  - unless @page.new_record?
    = form.text_field :full_path, :id => 'full-path', :disabled => true

= render 'admin/cms/partials/page_form_inner', :object => form

= render :partial => 'admin/cms/categories/form', :object => form

= render :partial => 'form_blocks'

= form.check_box :is_published, :label => "Published"

= render 'admin/cms/partials/page_form_after', :object => form

.form-actions
  = form.submit "Preview", :name => 'preview', :id => nil, :class => 'btn'
  = form.submit "Update", :class => 'btn btn-primary'

app/views/admin/datasets/_index_branch.html.haml
- page ||= index_branch

%li{:id => dom_id(page), "ng-controller" => "ListCtrl", "ng-show" => "matchSearch()", "ng-init" => "init('#{page.label.downcase}')"}
  .item
    .icon{:class => page.is_published?? 'published' : 'draft'}

    .btn-group
      = link_to t('.edit'), edit_admin_dataset_path(page), :class => 'btn btn-sm btn-default'
      = link_to t('.delete'), admin_dataset_path(page), :method => :delete, :data => {:confirm => "Are you sure?"}, :class => 'btn btn-sm btn-danger'

    .item-content
      .item-title
        = link_to page.label, edit_admin_dataset_path(page), :class => 'item-label'
      .item-meta
        = link_to page.url, page.url, :target => '_blank'
        = render partial: "editions", locals: {page: page}

app/views/admin/datasets/edit.html.haml
.page-header
  %h2 Editing Dataset

= comfy_form_for @page, :as => :page, :url => {:action => :update}, :html => {:multipart => true} do |form|
  = render form

app/views/admin/datasets/index.html.haml
.page-header
  = link_to "Add dataset", new_admin_dataset_path, :class => 'btn btn-default pull-right'
  %h2 Datasets

= comfy_form_for @page, :as => :page, url: admin_dataset_path(@page), :html => {:multipart => true} do |form|
  = render form

= render 'comfy/admin/cms/partials/pages_before'

%ul.list{"ng-app" => "SearchableList"}
  %input{:type => "text", "ng-model" => "pattern", :placeholder => "Search Datasets", class: 'form-control'}
  = render :partial => 'index_branch', :collection => @pages, :editions => @editions

= render 'comfy/admin/cms/partials/pages_after'