config/routes.rb
UnepWcmcOrg::Application.routes.draw do

  as :user do
    patch '/user/confirmation' => 'confirmations#update', via: :patch, as: :update_user_confirmation
    get 'users/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'registrations#update', :as => 'user_registration'
  end

  devise_for :users, :controllers => { :confirmations => "confirmations" }, skip: [:registrations]

  post '/donate/create', to: 'checkouts#create', as: 'checkouts'

  get "/about-us/news-archive" => redirect("/news")

  namespace :admin do
    resources :employees do
      collection do
        put :reorder
      end
    end

    resources :aboutus_pages, except: [:new, :destroy]

    resources :expertise_pages

    resources :news_items do
      collection do
        put :reorder
      end
    end

    resources :programmes, except: [:show]

    resources :featured_projects do
      collection do
        put :reorder
      end
    end

    resources :datasets do
      collection do
        put :reorder
      end
    end

    resources :policies do
      collection do
        put :reorder
      end
    end

    resources :vacancies do
      collection do
        put :reorder
      end
    end

    resources :users
  end

  resources :forms, only: [] do
    resources :submissions, path: "applications", except: [:index]
  end

  resources :job_applications, only: [:index, :show, :destroy]

  get '/download_all_applications_zip/:id', controller: :job_applications, action: :download_all_applications_zip, as: 'download_all_applications_zip'
  get '/download_all_applications_csv/:id', controller: :job_applications, action: :download_all_applications_csv, as: 'download_all_applications_csv'
  get '/download_application_zip/:id', controller: :job_applications, action: :download_application_zip, as: 'download_application_zip'

  namespace :api do
    resources :geoip, only: [:index]
    resources :countries, only: [:index]
    resources :employees, only: [:index]
  end

  get 'test_exception_notifier', controller: :application, action: :test_exception_notifier

  comfy_route :cms_admin, :path => '/admin'
  comfy_route :cms, :path => '/', :sitemap => true
end

app/models/vacancy.rb
class Vacancy < Comfy::Cms::Page

  has_many :forms

  def formatted_label
    job_code = label.scan(/\((.*)\)/)
    return "unknown_job_code" unless job_code.present?
    job_code.first.first.parameterize.underscore
  end

end

app/controllers/admin/vacancies_controller.rb
class Admin::VacanciesController < Admin::PageResourcesController
  before_action :set_form, only: [:edit, :update]
  before_action :build_form, only: [:create]
  before_action :set_vacancy_fields, only: [:edit, :create]

  private

  def save_resources
    if @page.save
      @form.update(form_params.merge(vacancy_id: @page.id))
      vacancy_fields.save
    else
      false
    end
  end

  def site_identifier
    'vacancies'
  end

  def layout_identifier
    'vacancy'
  end

  def set_form
    @form = Form.where(vacancy_id: @page.id).first
  end

  def build_form
    @form = Form.new(vacancy_id: @page.id)
  end

  def form_params
    params[:form].try(:permit, fields_attributes: [:_destroy, :name, :id, :type], attachments_attributes: [:_destroy, :name, :id, :file]) || {}
  end

  def set_vacancy_fields
    @vacancy_fields ||= VacancyField.for_vacancy(@page)
  end

  def vacancy_fields_params
    params[:vacancyFieldForms].try(:values) || []
  end

  def vacancy_fields
    VacancyFieldsBuilder.new(fields_params: vacancy_fields_params,
      vacancy: @page)
  end
end

app/views/comfy/admin/vacancies/_custom_fields.html.haml
.control-group{ "ng-app" => "PracticalQuestionForm", "ng-controller" => "FormCtrl", "ng-init" => "init(#{render partial: "fields", formats: :json}, #{render partial: "attachments", formats: :json}, #{render partial: "vacancy_fields", formats: :json})"}
  %label.control-label Practical Question Fields
  .control-group{ "ng-repeat" => "form in fieldForms", "ng-show" => "!form.removed" }
    .controls
      .control-group
        %label.control-label{:for => "form[fields_attributes][{{ fieldFormIndex() }}][name]"} Label
        .controls
          %input{ :type => "text", "ng-model" => "form.label", :name => "form[fields_attributes][{{ fieldFormIndex() }}][name]" }
          %input{ :type => "hidden", "ng-model" => "form.id", :name => "form[fields_attributes][{{ fieldFormIndex() }}][id]", "ng-if" => "form.id", "value" => "{{ form.id }}"}
          %input{ :type => "hidden", :name => "form[fields_attributes][{{ fieldFormIndex() }}][_destroy]", "ng-if" => "form.removed", :value => '1' }
      .control-group
        %label.control-label{:form => "form[fields_attributes][{{ fieldFormIndex() }}][type]"} Type
        .controls
          %select{ "ng-model" => "form.type", "name" => "form[fields_attributes][{{ fieldFormIndex() }}][type]"}
            %option{ :value => "FileField", "ng-selected" => "form.type == 'FileField'" }
              File field
            %option{ :value => "TextField", "ng-selected" => "form.type == 'TextField'" }
              Text field
      .control-group
        .controls
          %input.btn.btn-danger{:type => "button", :value => "Remove", "ng-click" => "removeFieldForm()"}

  .control-group
    .controls
      %input.btn{:type => "button", :value => "Add a field", "ng-click" => "addField()"}

  %label.control-label Practical Question Attachments
  .control-group{ "ng-repeat" => "form in attachmentForms", "ng-show" => "!form.removed" }
    .controls
      .control-group
        %label.control-label{:for => "form[attachments_attributes][{{ attachmentFormIndex() }}][name]"} Name
        .controls
          %input{ :type => "text", "ng-model" => "form.name", :name => "form[attachments_attributes][{{ attachmentFormIndex() }}][name]" }
          %input{ :type => "hidden", "ng-model" => "form.id", :name => "form[attachments_attributes][{{ attachmentFormIndex() }}][id]", "ng-if" => "form.id", "value" => "{{ form.id }}"}
          %input{ :type => "hidden", :name => "form[attachments_attributes][{{ attachmentFormIndex() }}][_destroy]", "ng-if" => "form.removed", :value => '1' }
      .control-group
        %label.control-label{:for => "form[attachments_attributes][{{ fieldFormIndex() }}][type]"} File
        .controls
          %input{ :type => "file", :name => "form[attachments_attributes][{{ attachmentFormIndex() }}][file]" }
          %a{ :href => "{{ form.url }}", "ng-if" => "form.url"}
            %p {{ form.filename }}
      .control-group
        .controls
          %input.btn.btn-danger{:type => "button", :value => "Remove", "ng-click" => "removeAttachmentForm()"}

  .control-group
    .controls
      %input.btn{:type => "button", :value => "Add an attachment", "ng-click" => "addAttachment()"}

  %hr
  %label.control-label Attach files to the vacancy (eg: Person specification)
  .control-group{ "ng-repeat" => "form in vacancyFieldForms", "ng-show" => "!form.removed" }
    .controls
      .control-group
        %label.control-label{:for => "vacancyFieldForms[{{ vacancyFieldFormIndex() }}][label]"} Label
        .controls
          %select{ "ui-select2" => true, "ng-model" => "form.label", "name" => "vacancyFieldForms[{{ vacancyFieldFormIndex() }}][label]", "ng-change" => "clearCustomLabel(vacancyFieldFormIndex())" }
            %option{"ng-repeat" => "option in vacancyFieldSelectDefaultOptions", :value => "{{ option }}", "ng-selected" => "form.label == '{{ option }}' "}
              {{ option }}
            %option{:value => "Custom label", "ng-selected" => "form.label == 'Custom label'" }
              Custom label
        .controls
          %input{ :type => "text", "ng-model" => "form.custom_label", :name => "vacancyFieldForms[{{ vacancyFieldFormIndex() }}][custom_label]", "ng-show" => "showLabelInput(form)"}
          %input{ :type => "hidden", "ng-model" => "form.id", :name => "vacancyFieldForms[{{ vacancyFieldFormIndex() }}][id]", "ng-if" => "form.id", "value" => "{{ form.id }}"}
          %input{ :type => "hidden", "ng-model" => "form.removed", :name => "vacancyFieldForms[{{ vacancyFieldFormIndex() }}][removed]", "ng-if" => "form.removed", "value" => "{{ form.removed }}"}

      .control-group
        %label.control-label{:for => "vacancyFieldForms[{{ vacancyFieldFormIndex() }}][file]"} File
        .controls
          %input{ :type => "file", "ng-model" => "form.file", :name => "vacancyFieldForms[{{ vacancyFieldFormIndex() }}][file]" }
          %a{ :href => "{{ form.url }}", "ng-if" => "form.url"}
            %p {{ form.filename }}
      .control-group
        .controls
          %input.btn.btn-danger{:type => "button", :value => "Remove", "ng-click" => "removeVacancyFieldForm(vacancyFieldFormIndex())" }

  .control-group
    .controls
      %input.btn{:type => "button", :value => "Add a file", "ng-click" => "addVacancyField()" }

app/views/comfy/admin/vacancies/_index_branch.html.haml
- page ||= index_branch

%li{:id => dom_id(page)}
  .item
    .icon{:class => page.is_published?? 'published' : 'draft'}
      .dragger
        %span &#8645;

    .btn-group
      = link_to t('.edit'), edit_admin_vacancy_path(page), :class => 'btn btn-small'
      = link_to t('.delete'), admin_vacancy_path(page), :method => :delete, :data => {:confirm => "Are you sure?"}, :class => 'btn btn-small btn-danger'

    .item-content
      .item-title
        = link_to page.label, edit_admin_vacancy_path(page), :class => 'item-label'
      .item-meta
        = link_to page.url, page.url, :target => '_blank'
        = render partial: "editions", locals: {page: page}

app/views/comfy/admin/vacancies/index.html.haml
.page-header
  = link_to "Add a vacancy", new_admin_vacancy_path, :class => 'btn pull-right'
  %h2 Vacancies

= comfy_form_for @page, :as => :page, url: admin_vacancy_path(@page), :html => {:multipart => true} do |form|
  = render form

= render 'admin/cms/partials/pages_before'

%ul.list.sortable
  = render :partial => 'index_branch', :collection => @pages

= render 'admin/cms/partials/pages_after'